services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=mechaniq'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5436:5432"
    networks:
      - main_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=pgadmin@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=root'
    volumes:
      - ./backend/pgAdminConfig/servers.json:/pgadmin4/servers.json
      - ./backend/pgAdminConfig/pgpass:/pgadmin4/.pgpass
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - main_network
  backend:
    image: 'openjdk:21-jdk'
    container_name: 'spring-boot'
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./backend/:/app
    working_dir: /app
    command: >
      sh -c " ./mvnw spring-boot:run -Dspring-boot.run.profiles=remote -Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"
    depends_on:
      - postgres
    networks:
      - main_network
volumes:
  postgres-data:
    driver: local
networks:
  main_network:

